export const makeShareable = jest.fn((value: unknown) => value);
export const makeShareableCloneOnUIRecursive = jest.fn((value: unknown) => value);
export const makeShareableCloneRecursive = jest.fn((value: unknown) => value);
export const isShareableRef = jest.fn(() => false);
export const isShareable = jest.fn(() => false);
export const isSynchronizable = jest.fn(() => false);
export const shareableMappingCache = { has: jest.fn(), get: jest.fn(), set: jest.fn() };
export const serializableMappingCache = { has: jest.fn(), get: jest.fn(), set: jest.fn() };
export const callMicrotasks = jest.fn();
export const getDynamicFeatureFlag = jest.fn();
export const getStaticFeatureFlag = jest.fn();
export const setDynamicFeatureFlag = jest.fn();
export const createSerializable = jest.fn((value: unknown) => value);
export const isSerializableRef = jest.fn(() => false);
export const registerCustomSerializable = jest.fn();
export const createShareable = jest.fn((value: unknown) => value);
export const createSynchronizable = jest.fn((value: unknown) => value);
export const getRuntimeKind = jest.fn(() => 'js');
export const isRNRuntime = jest.fn(() => true);
export const isUIRuntime = jest.fn(() => false);
export const isWorkerRuntime = jest.fn(() => false);
export const isWorkletRuntime = jest.fn(() => false);
export const RuntimeKind = { UI: 'UI', RN: 'RN', Worker: 'Worker' };
export const createWorkletRuntime = jest.fn();
export const getUIRuntimeHolder = jest.fn();
export const getUISchedulerHolder = jest.fn();
export const runOnRuntime = jest.fn();
export const runOnRuntimeAsync = jest.fn();
export const runOnRuntimeSync = jest.fn();
export const runOnRuntimeSyncWithId = jest.fn();
export const scheduleOnRuntime = jest.fn();
export const scheduleOnRuntimeWithId = jest.fn();
export const UIRuntimeId = 0;
export const executeOnUIRuntimeSync = jest.fn((fn: () => unknown) => fn());
export const runOnJS = jest.fn((fn: (...args: unknown[]) => unknown) => fn);
export const runOnUI = jest.fn((fn: (...args: unknown[]) => unknown) => fn);
export const runOnUIAsync = jest.fn();
export const runOnUISync = jest.fn((fn: () => unknown) => fn());
export const scheduleOnRN = jest.fn();
export const scheduleOnUI = jest.fn();
export const isWorkletFunction = jest.fn(() => false);
export const WorkletsModule = {};
